services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /go/src/secrets/service-account-credentials.json
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-phraze}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - 8080:3000
    volumes:
      - type: bind
        source: ./app
        target: /go/src/app
      - type: bind
        source: ./secrets
        target: /go/src/secrets
        read_only: true
      - type: volume
        source: go-modules
        target: /go/pkg/mod
  
  db:
    image: postgres:16
    shm_size: 128mb
    ports: 
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-phraze}
    volumes:
      - db-store:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d phraze
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s

volumes:
  db-store:
  go-modules: