package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/RyoheiTomiyama/phraze-api/router/graph/model"
)

// Decks is the resolver for the decks field.
func (r *queryResolver) Decks(ctx context.Context) ([]*model.Deck, error) {
	panic(fmt.Errorf("not implemented: Decks - decks"))
}

// Deck is the resolver for the deck field.
func (r *queryResolver) Deck(ctx context.Context, id string) (*model.Deck, error) {
	panic(fmt.Errorf("not implemented: Deck - deck"))
}
