package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/RyoheiTomiyama/phraze-api/router/graph/model"
)

// DeleteDeck is the resolver for the deleteDeck field.
func (r *mutationResolver) DeleteDeck(ctx context.Context, input model.DeleteDeckInput) (*model.DeleteDeckOutput, error) {
	panic(fmt.Errorf("not implemented: DeleteDeck - deleteDeck"))
}
