package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/RyoheiTomiyama/phraze-api/router/graph/model"
	"github.com/RyoheiTomiyama/phraze-api/util/errutil"
)

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, input model.DeleteCardInput) (*model.DeleteCardOutput, error) {
	ar, err := r.cardUsecase.DeleteCard(ctx, input.ID)
	if err != nil {
		return nil, errutil.Wrap(err)
	}

	return &model.DeleteCardOutput{AffectedRows: int(ar)}, nil
}
