package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/RyoheiTomiyama/phraze-api/router/graph/model"
	"github.com/RyoheiTomiyama/phraze-api/util/errutil"
)

// ReviewCard is the resolver for the reviewCard field.
func (r *mutationResolver) ReviewCard(ctx context.Context, input model.ReviewCardInput) (*model.ReviewCardOutput, error) {
	if err := input.Validate(ctx); err != nil {
		return nil, errutil.Wrap(err)
	}

	if err := r.cardUsecase.ReviewCard(ctx, input.CardID, input.Grade); err != nil {
		return nil, errutil.Wrap(err)
	}

	return &model.ReviewCardOutput{CardID: input.CardID}, nil
}
