package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	graph "github.com/RyoheiTomiyama/phraze-api/infra/graph/generated"
	"github.com/RyoheiTomiyama/phraze-api/infra/graph/model"
)

// Health is the resolver for the health field.
func (r *mutationResolver) Health(ctx context.Context) (*model.Health, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
