-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";

-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';

-- ユーザー
CREATE TABLE
    "public"."users" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "name" character varying(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("id")
    );

-- デッキ
CREATE TABLE
    "public"."decks" (
        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL REFERENCES users (id),
        deck_name VARCHAR(100) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("id")
    );

-- カード
CREATE TABLE
    "public"."cards" (
        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        deck_id bigint NOT NULL REFERENCES decks (id),
        question TEXT NOT NULL,
        answer TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("id")
    );

-- トリガー関数の作成
CREATE
OR REPLACE FUNCTION update_timestamp () RETURNS TRIGGER AS '
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
' LANGUAGE plpgsql;

-- トリガーの作成
CREATE TRIGGER update_users_updated_at BEFORE
UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_timestamp ();

CREATE TRIGGER update_decks_updated_at BEFORE
UPDATE ON decks FOR EACH ROW EXECUTE FUNCTION update_timestamp ();

CREATE TRIGGER update_cards_updated_at BEFORE
UPDATE ON cards FOR EACH ROW EXECUTE FUNCTION update_timestamp ();