-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";

-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';

-- デッキ
CREATE TABLE
    "public"."decks" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "user_id" TEXT NOT NULL,
        "name" VARCHAR(100) NOT NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("id")
    );

-- カード
CREATE TABLE
    "public"."cards" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "deck_id" bigint NOT NULL REFERENCES decks (id),
        "question" TEXT NOT NULL,
        "answer" TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY ("id")
    );

-- トリガー関数の作成
CREATE
OR REPLACE FUNCTION update_timestamp () RETURNS TRIGGER AS '
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
' LANGUAGE plpgsql;

-- トリガーの作成
CREATE TRIGGER update_decks_updated_at BEFORE
UPDATE ON decks FOR EACH ROW EXECUTE FUNCTION update_timestamp ();

CREATE TRIGGER update_cards_updated_at BEFORE
UPDATE ON cards FOR EACH ROW EXECUTE FUNCTION update_timestamp ();

--　カード評価結果
CREATE TABLE
    "public"."card_reviews" (
        "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "card_id" BIGINT NOT NULL REFERENCES cards (id),
        "reviewed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "grade" INT NOT NULL CHECK (grade BETWEEN 1 AND 5),
        PRIMARY KEY (id)
    );

-- 次のカード学習情報
CREATE TABLE
    "public"."card_schedules" (
        "card_id" BIGINT NOT NULL REFERENCES cards (id),
        "schedule_at" TIMESTAMP NOT NULL,
        "interval" INT NOT NULL, -- 復習間隔（MINUTE）
        "efactor" FLOAT NOT NULL, -- イーファクター
        PRIMARY KEY (card_id)
    );

CREATE INDEX idx_card_schedules_schedule_at ON "card_schedules" ("schedule_at");