name: Test

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "app/*"
      - "atlas/*"
      - ".github/workflows/test.yaml"

env:
  GO_VERSION: 1.22
  TZ: UTC
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: phraze_test

jobs:
  test:
    name: Go API Tests
    runs-on: ubuntu-latest
    container: golang:${{ github.env.GO_VERSION }}
    services:
      db:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: ${{ env.POSTGRES_HOST}}
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U ${{ github.env.POSTGRES_USER }} -d ${{ github.env.POSTGRES_DB }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('./app/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: make test

  graphql-inspector:
    name: GraphQL Inspector
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: graphql-hive/graphql-inspector@v3.4.0
        with:
          schema: "{{ github.base_ref }}:./app/router/graph/schema/**/*.graphqls"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
