name: Test

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "app/*"
      - "atlas/*"
      - ".github/workflows/test.yaml"

env:
  TZ: UTC
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: phraze_test

jobs:
  test:
    name: Go API Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./app/go.mod
          cache-dependency-path: ./app/go.sum

      - name: Setup Atlas
        uses: ariga/setup-atlas@v0.2

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

  graphql-inspector:
    name: GraphQL Inspector
    runs-on: ubuntu-latest
    # permissions:
    #   actions: write
    #   checks: write
    #   contents: read
    #   packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: pwd
      - run: ls -la

      - uses: graphql-hive/graphql-inspector@v3.4.0
        with:
          schema: "${{ github.base_ref }}:./app/router/graph/schema/*.graphqls"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
